version: '3.8'
services:
  postgres_db:
    image: postgres:15-alpine
    container_name: bebras_db
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: bebras_bolivia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  usuario-service:
    build:
      context: .
      dockerfile: servicios/servicio-usuario/Dockerfile
    container_name: usuario_svc
    volumes:
      - ./servicios/servicio-usuario:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://dev_user:dev_password@postgres_db:5432/bebras_bolivia
    ports:
      - "4102:4102"
    depends_on:
      - postgres_db

  cliente:
    build:
      context: .
      dockerfile: cliente/Dockerfile
    container_name: bebras_frontend
    volumes:
      - ./cliente:/usr/src/app/cliente
      - /usr/src/app/cliente/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://usuario-service:4102
    ports:
      - "3000:3000"
    depends_on:
      - usuario-service
      - postgres_db

volumes:
  postgres_data:
