version: '3.8'
services:
  postgres_db:
    image: postgres:15-alpine
    container_name: bebras_db
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: bebras_bolivia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: .
      dockerfile: servicios/servicio-autenticacion/Dockerfile
    container_name: auth_svc
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_URL=postgres://dev_user:dev_password@postgres_db:5432/bebras_bolivia
    ports:
      - "3001:3001"
    depends_on:
      - postgres_db

  cliente:
    build:
      context: .
      dockerfile: cliente/Dockerfile
    container_name: bebras_frontend
    volumes:
      - ./cliente:/usr/src/app/cliente
      - /usr/src/app/cliente/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://auth-service:3001
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - postgres_db

volumes:
  postgres_data:
